#!/usr/bin/env node

// Test script to simulate login and debug issues

const bcrypt = require('bcryptjs');

async function testLogin() {
    console.log('🔍 Testing login logic...\n');

    // Test credentials that should exist from the server logs
    const testCredentials = [
        { email: 'mudjanimaismael100@gmail.com', username: 'js_1n5i4tw_hrm0' },
        { email: 'allyismael2002@gmail.com', username: 'js_1n5i6ge_d3kj' }
    ];

    // Test if bcrypt comparison works
    const testPassword = 'TestPassword123!';
    const testHash = await bcrypt.hash(testPassword, 12);
    
    console.log('🔐 Password hash test:');
    console.log('   Original password:', testPassword);
    console.log('   Generated hash:', testHash);
    
    const isValid = await bcrypt.compare(testPassword, testHash);
    console.log('   Verification result:', isValid ? '✅ PASS' : '❌ FAIL');
    
    // Test with wrong password
    const isInvalid = await bcrypt.compare('WrongPassword', testHash);
    console.log('   Wrong password test:', isInvalid ? '❌ SHOULD FAIL' : '✅ CORRECTLY REJECTED');

    console.log('\n📧 Test credentials generated by server:');
    testCredentials.forEach((cred, index) => {
        console.log(`   ${index + 1}. Email: ${cred.email}`);
        console.log(`      Username: ${cred.username}`);
    });

    console.log('\n💡 To test login:');
    console.log('   1. Check your email for the generated username and password');
    console.log('   2. Use those exact credentials in the login form');
    console.log('   3. Make sure your email has been verified first');
    
    console.log('\n🔧 Debug suggestions:');
    console.log('   - Check server logs for "Login attempt for:" messages');
    console.log('   - Verify the verification token was processed');
    console.log('   - Confirm the user status is "active" in database');
}

testLogin().catch(console.error);